<div class="tvd-modal-content">
    <h4>
        <#= post_title #>
    </h4>
    <p>
        <?php echo __('This setting determines how much time it takes before the same visitor will be shown the same form again', 'thrive-leads') ?>
    </p>

    <p>
        <?php echo __('Show once every:', 'thrive-leads') ?>
    </p>

    <div class="tvd-row tvd-collapse">
        <div class="tvd-col tvd-s8">
            <div class="tvd-slider-widget" data-min="0" data-max="100" data-connect-to="#display_frequency_input" data-value="<#= display_frequency #>"></div>
        </div>
        <div class="tvd-col tvd-s4">
            <div class="tvd-row tvd-collapse tvd-no-margin-bottom">
                <div class="tvd-col tvd-s8">
                    <div class="tvd-input-field">
                        <input class="input-display-frequency trigger-config tvd-no-margin" id="display_frequency_input" type="text" name="display_frequency"
                               size="3" tabindex="1">
                    </div>
                </div>
                <div class="tvd-col tvd-s4">
                <span class="tvd-vertical-align">
                    <?php echo __('days', 'thrive-leads') ?>
                </span>
                </div>
            </div>
        </div>
    </div>
    <p>
        <?php echo __('*If set to zero then the popup will be displayed all the time', 'thrive-leads') ?>
    </p>
</div>
<div class="tvd-modal-footer">
    <div class="tvd-row">
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-modal-close tvd-waves-effect"
               tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
        </div>
        <div class="tvd-col tvd-s12 tvd-m6">
            <a href="javascript:void(0)" class="tvd-waves-effect tvd-waves-light tvd-btn tvd-btn-green tvd-right tve-save-frequency tvd-modal-submit"
               tabindex="2"><?php echo __('Save', 'thrive-leads') ?></a>
        </div>
    </div>
</div>