<ul class="tvd-collection tvd-with-header" id="tve-table-items">
    <li class="tvd-collection-header">
        <div class="tvd-row">
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Source', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el"><?php echo __('Source', 'thrive-leads'); ?></h5>
                </div>
            </div>
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Type', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el"><?php echo __('Type', 'thrive-leads'); ?></h5>
                </div>
            </div>
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Impressions', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el tve-table-sortable" data-order-by="impressions"><?php echo __('Impressions', 'thrive-leads'); ?></h5>
                </div>
            </div>
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Conversions', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el tve-table-sortable" data-order-by="conversions"><?php echo __('Conversions', 'thrive-leads'); ?></h5>
                </div>
            </div>
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('Conversion Rate', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el tve-table-sortable" data-order-by="conversion_rate"><?php echo __('Conversion Rate', 'thrive-leads'); ?></h5>
                </div>
            </div>
            <div class="tvd-col tvd-s2">
                <div class="tvd-truncate-on-small" data-popup="<?php echo __('New Leads', 'thrive-leads'); ?>">
                    <h5 class="tvd-truncate-on-small-el tve-table-sortable" data-order-by="leads"><?php echo __('New Leads', 'thrive-leads'); ?></h5>
                </div>
            </div>
        </div>
    </li>
</ul>